#PAYPAL_API_USERNAME = 'xxx.xxx.xx'
#PAYPAL_API_PASSWORD = 'xxx'
#PAYPAL_API_SIGNATURE = 'xxx'

PAYPAL_API_USERNAME = 'paiuolo-facilitator_api1.gmail.com'
PAYPAL_API_PASSWORD = '9NF92X47LF3N5R9R'
PAYPAL_API_SIGNATURE = 'An5ns1Kso7MWUdW4ErQKJJJ4qi4-Ac3Z1OSxD085QxXZMinLY3ERZ5JC'