# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_subscribed',
            field=models.BooleanField(default=True, help_text='Subscribe to our newsletter', verbose_name='Newsletter subscribed'),
        ),
    ]
