# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20160218_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='background_color',
            field=models.CharField(blank=True, max_length=9, verbose_name='background color'),
        ),
    ]
