# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 21:09
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0008_auto_20160119_1718'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/series')),
            ],
            options={
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('virtual', models.BooleanField(default=False, verbose_name='Virtual')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'book format',
                'verbose_name_plural': 'book formats',
            },
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'book store',
                'verbose_name_plural': 'book stores',
            },
        ),
        migrations.CreateModel(
            name='DigitalDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('downloads_remaining', models.PositiveIntegerField(default=5)),
                ('log', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Digital goods',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/series')),
                ('background_color', models.CharField(blank=True, max_length=9, verbose_name='background color')),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
    ]
