# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='background_color',
            field=models.CharField(blank=True, max_length=9, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/series'),
        ),
    ]
